dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 7.1

env:
  - VERSION=HEAD
  - VERSION=3.2.0
  # The final CI slot should be used to test the update path from the oldest
  # available database fixture.
  - VERSION=1.0.0-rc2

addons:
  chrome: stable

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - google-chrome-stable --version

install:
  # Install ORCA so that we can build the fixture using that.
  - git clone --depth 1 git@github.com:acquia/orca.git ../orca

  - ORCA=$TRAVIS_BUILD_DIR/../orca
  - ORCA_FIXTURE=$ORCA-build

  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export PATH="$ORCA/bin:$PATH"
  - export PATH="$ORCA/vendor/bin:$PATH"
  - export PATH="$ORCA_FIXTURE/vendor/bin:$PATH"

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Require Prestissimo to speed up Composer.
  - composer global require hirak/prestissimo

  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - yes '' | pecl install yaml
  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Use ORCA to build the code base.
  - cd ../orca
  - composer install
  - orca fixture:init --force --sut-only --sut drupal/lightning_workflow
  - # Install dev dependencies.
  - composer require --dev drupal/inline_entity_form --working-dir $ORCA_FIXTURE

before_script:
  - cd $ORCA_FIXTURE/docroot
  - $TRAVIS_BUILD_DIR/update.sh $VERSION
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - chromedriver --port=4444 &

script:
  - orca tests:run --no-servers --sut-only --sut drupal/lightning_workflow

after_failure:
  - cd docroot
  - drush watchdog:show --count=100 --severity=Error --extended
